#!/usr/bin/env python3

from game.simulation import Simulation

if __name__ == '__main__':
    try:
        for output in Simulation():
            print(output)
    except (KeyboardInterrupt, EOFError):
        pass
